version: '2.1'
networks:
  backing-services:
    driver: bridge
services:
  # https://hub.docker.com/_/mongo
  mongo:
    # image: healthcheck/mongo:latest
    image: mongo:4.0.14-xenial
    environment:
      MONGO_PORT_27017_TCP_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: bookstore
      MONGO_INITDB_ROOT_PASSWORD: bookstore
    ports: ['27017:27017']
    networks: [backing-services]
    healthcheck:
      test: test `pgrep mongo` -eq 1 || exit 1
      interval: 1s
      retries: 33
      timeout: 1s
  # https://hub.docker.com/_/mongo-express
  mongo-express:
    depends_on:
      mongo:
        condition: service_healthy
    image: mongo-express:0.49.0
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: bookstore
      ME_CONFIG_MONGODB_ADMINPASSWORD: bookstore
      ME_CONFIG_MONGODB_AUTH_DATABASE: bookstore
      ME_CONFIG_MONGODB_AUTH_USERNAME: bookstore
      ME_CONFIG_MONGODB_AUTH_PASSWORD: bookstore
      ME_CONFIG_BASICAUTH_USERNAME: bookstore
      ME_CONFIG_BASICAUTH_PASSWORD: bookstore
    ports: ['8081:8081']
    networks: [backing-services]
